export const initialForm = {
  maxWidth: 1000,
  sections: [
    {
      sectionTitle: "Personal Information",
      position: 0,
      containers: [
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 0,
          fields: [
            {
              fieldType: "profileImage",
              title: "image",
              columnName: "image",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 1,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "select your image",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 1,
          fields: [
            {
              fieldType: "textField",
              title: "firstName",
              columnName: "firstName",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 0,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter First Name",
              regex: ".*[^A-Za-z ].*",
            },
            {
              fieldType: "textField",
              title: "lastName",
              columnName: "lastName",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 1,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter Last Name",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 2,
          fields: [
            {
              fieldType: "textField",
              title: "email",
              columnName: "email",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 0,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter Email Address",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 3,
          fields: [
            {
              fieldType: "textField",
              title: "primaryMobile",
              columnName: "primaryMobile",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 0,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter Contact Number",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 4,
          fields: [
            {
              fieldType: "singleSelectDropDown",
              title: "gender",
              columnName: "gender",
              isRequired: true,
              answer: "male",
              minLimit: 4,
              maxLimit: 30,
              position: 0,
              options: [
                { optionId: 1, optionName: "male" },
                { optionId: 2, optionName: "female" },
                { optionId: 3, optionName: "others" },
              ],
              allowsMultipleSelection: false,
              errorMessage: "Select your gender",
              regex: ".*[^A-Za-z ].*",
            },
            {
              fieldType: "textField",
              title: "dob",
              columnName: "dob",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 1,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter dob",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
      ],
    },
    {
      sectionTitle: "Additional Information",
      position: 1,
      containers: [
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 0,
          fields: [
            {
              fieldType: "textField",
              title: "addressLine1",
              columnName: "addressLine1",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 0,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter AddressLine1",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 1,
          fields: [
            {
              fieldType: "textField",
              title: "addressLine2",
              columnName: "addressLine2",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 0,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter AddressLine2",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 2,
          fields: [
            {
              fieldType: "textField",
              title: "city",
              columnName: "city",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 0,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter city Name",
              regex: ".*[^A-Za-z ].*",
            },
            {
              fieldType: "textField",
              title: "postalCode",
              columnName: "postalCode",
              isRequired: true,
              answer: "",
              minLimit: 4,
              maxLimit: 500,
              position: 1,
              options: [],
              allowsMultipleSelection: false,
              errorMessage: "Enter PostalCode",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
        {
          containerType: "oneField",
          containerDirection: "horizontal",
          contentAdjustment: "equalSpacing",
          position: 3,
          fields: [
            {
              fieldType: "singleSelectDropDown",
              title: "country",
              columnName: "country",
              isRequired: true,
              answer: "Pakistan",
              minLimit: 4,
              maxLimit: 30,
              position: 0,
              options: [
                { optionId: 1, optionName: "Pakistan" },
                { optionId: 2, optionName: "United Kingdom" },
                { optionId: 3, optionName: "United States" },
              ],
              allowsMultipleSelection: false,
              errorMessage: "Select your country",
              regex: ".*[^A-Za-z ].*",
            },
          ],
        },
      ],
    },
  ],
};
